version: 2.1

orbs:
  node: circleci/node@4.7
  
jobs:
  test:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test
    


workflows:
  test: 
    jobs:
      - test
  