version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  test:
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
  