version: 2.1

orbs:
  node: circleci/node@4.7
  
jobs:
  test-grit:
    docker:
      - image: cimg/node:17.4.0
    resource_class: large
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test 

workflows:
  test: 
    jobs:
      - test-grit

  